### PR TITLE
feat: merge `models` discovery into the `model` noun + deprecation-alias helper (BE-2999)

### PR DESCRIPTION
**Pull request by mattmillerai**
## ELI-5

`comfy` had two confusingly-split command groups: `comfy model` (singular — your
local model files on disk: download / remove / list) and `comfy models` (plural —
asking a backend/cloud server what models exist: list-folders / list-folder /
search / show). Two nouns for "models" is easy to fumble, and `model list` vs
`models list-folder` read like typos of each other.

This merges everything under the single `model` noun. Now `comfy model search`,
`comfy model show`, `comfy model list-folders`, and `comfy model list-folder` all
work. The old `comfy models …` spelling still works exactly as before, but it's
hidden from `--help` and prints a one-line yellow "deprecated; use `comfy model …`"
warning to stderr. Nothing breaks.

## What changed

- **New shared helper `comfy_cli/deprecation.py`** — `add_deprecated_alias(parent,
  source_app, old_name, new_name)` mounts a hidden alias of a Typer group whose
  group help is prefixed `[DEPRECATED — use <new>]` and which emits a single
  `[yellow]` warning to **stderr** on invocation (never silenced — the warning is
  the point, and stderr keeps the JSON-envelope-on-stdout contract intact). The
  sibling noun consolidations reuse this helper.
- **`model` now owns the discovery leaves** — the four leaves are surfaced under
  `comfy model` by borrowing `search.app`'s command registrations (the same
  `CommandInfo` objects — the implementations are reused, not duplicated). This
  mirrors the existing `skill`/`skills` alias reuse pattern.
- **`models` is a hidden, deprecated alias** wired through the new helper; its four
  leaves still work and print the warning.
- **Help text disambiguated** — `comfy model list` says "local models on disk";
  `list-folders`/`list-folder` say "backend/cloud", so `list` vs `list-folder` no
  longer reads as a typo.
- **Self-describing surface** — registered the canonical `comfy model …` paths in
  `COMMAND_SCHEMAS` (keeping the plural too, since the emitted envelope `command`
  field still carries `models …`, so both spellings must resolve — same dual-reg
  as `skill`/`skills`). Updated the bundled `SKILL.md` examples to the canonical
  spelling.

## Non-breaking

Yes. Every old `comfy models …` invocation still works via the alias, and the JSON
envelope `command` field is unchanged (`models list-folders`, etc.) — no contract
change for JSON consumers.

## Tests

- New `tests/comfy_cli/command/models/test_model_alias.py`: asserts the four
  discovery leaves resolve under `comfy model`; the local ops (download/remove/list)
  are undisplaced; `comfy models …` still resolves but is hidden with the deprecation
  banner; unit tests for the helper; and end-to-end that `comfy models list-folders`
  emits an ok envelope on stdout **and** the warning on stderr, while
  `comfy model list-folders` is warning-free.
- Extended `tests/comfy_cli/output/test_discovery.py` to require the canonical
  `comfy model …` schema registrations alongside the plural.
- Full suite green: **2480 passed, 13 skipped**. `ruff format --check` + `ruff check`
  clean on all touched files. (The 14 pre-existing repo-wide `UP038` lint findings
  are in untouched files — not introduced here.)

## Judgment calls

- Kept the envelope `command` field as `models …` (not `model …`) to stay strictly
  non-breaking for JSON consumers; that's why both spellings are registered in
  `COMMAND_SCHEMAS`, exactly like the pre-existing `skill`/`skills` alias.
- `@tracking.track_command("models")` on the reused leaves is left as-is (a cosmetic
  analytics group label), out of scope for this rename.

### CODE REVIEW

**Comment by mattmillerai** [comment]
Addressed the one substantive point surfaced by the Cursor panel (its judge crashed with a `parse_error` and posted no formal thread, but the leaked reasoning flagged a real latent trap): `add_deprecated_alias` is documented as a reusable helper for the sibling noun consolidations, yet it only copied `registered_commands`, silently dropping nested sub-groups (`add_typer`) and the source app's own group callback.

Harmless for the current `models`→`model` mount (a flat, callback-less command tree — verified `search.py`'s `app` has 4 leaf commands, no sub-groups, no callback), but a robustness trap for future reuse. The helper now also carries `registered_groups` and, when the source declares a callback, composes it with the deprecation warning (`functools.wraps` preserves its option signature) instead of overriding it. Added regression tests for both cases (`test_alias_carries_nested_sub_groups`, `test_alias_composes_source_callback`). The `source_cb is None` path is byte-identical to before, so zero behavior change for the shipped feature.

The failing Windows `test` check was an infra flake, not code — `uv` couldn't remove `pydantic_core/_pydantic_core.cp312-win_amd64.pyd` during dependency install (`Access is denied. (os error 5)`), a Windows file-lock race in the install step; re-running.

**Comment by mattmillerai** [comment]
Re-ran the failed \`Windows Specific Commands\` job; it failed again in the **dependency-install** step (not the test run):

\`\`\`
error: failed to remove file `...\pydantic_core/_pydantic_core.cp312-win_amd64.pyd`: Access is denied. (os error 5)
→ CalledProcessError (uv pip install) → ImportError: cannot import name '__version__' from 'pydantic_core'
\`\`\`

Confirmed **repo-wide, pre-existing infra flake** — the same job is currently red on every open branch (be-3000, be-2994, be-2982, be-2978, be-3001, be-2975, …), so it is unrelated to this diff (model discovery + deprecation alias, no dependency changes). Fixing it belongs in the CI workflow, not this PR.

The `model`/`models` code itself is green: the 24 alias + discovery tests pass locally, and \`build\`, \`ruff_check\`, CodeQL, and Socket all pass. Nothing actionable remains on this PR.

File: comfy_cli/cmdline.py [hunk 1]
```diff
@@ -1612,12 +1613,20 @@ def standalone(
 
 
 generate_command.register_with(app)
-app.add_typer(models_command.app, name="model", help="Manage models.")
+# The `model` noun owns BOTH the local-filesystem ops (download/remove/list) and
+# the backend/cloud discovery leaves (list-folders/list-folder/search/show). The
+# discovery leaves are implemented on `models_search_command.app`; surface them
+# under `model` by borrowing their command registrations (same CommandInfo
+# objects — no logic duplication).
+models_command.app.registered_commands.extend(models_search_command.app.registered_commands)
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply comfy_cli/cmdline.py]: Fixed in c5db184: the canonical `model` mount now also `registered_groups.extend(...)` so sub-groups stay in lockstep with the alias. The group *callback* is intentionally not mirrored here — on the discovery-only alias it scopes to those leaves, but `model` also owns local ops (download/remove/list), so mounting discovery's group setup on the whole noun would leak it onto those; documented inline.

File: comfy_cli/deprecation.py [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+
+    if source_cb is None:
+
+        @alias.callback()
+        def _emit_deprecation_warning() -> None:
+            warn_deprecated(old_name, new_name)
+    else:
+
+        @alias.callback()
+        @functools.wraps(source_cb)
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply comfy_cli/deprecation.py:95]: Fixed in c5db184: after `functools.wraps` we now pre-resolve the source callback's hints with `typing.get_type_hints(source_cb, include_extras=True)` (against the source's own globals) and store the concrete types on the wrapper, so Typer no longer resolves source-local names against deprecation.py. `include_extras` preserves typer.Option/Argument `Annotated` metadata.

File: comfy_cli/deprecation.py [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+    (e.g. ``"model"``); the banner renders it as ``comfy <new_name>``.
+    """
+    banner = f"[DEPRECATED — use `comfy {new_name}`]"
+    original = (original_help or "").strip()
+    return f"{banner} {original}".strip()
+
+
+def warn_deprecated(old_name: str, new_name: str) -> None:
+    """Emit the one-line yellow deprecation warning to stderr."""
+    rprint(f"[yellow]'comfy {old_name} …' is deprecated; use 'comfy {new_name} …'[/yellow]")
```
[the remark this answers is not in the document]
Comment (mattmillerai) [reply comfy_cli/deprecation.py:44]: Fixed in c5db184: docstring point (c) and `warn_deprecated`'s docstring now qualify the destination — `rprint` goes to stdout in pretty mode and stderr only in JSON/NDJSON mode.

**Comment by mattmillerai** [comment]
Resolver pass — **nothing actionable left on this PR; it is ready to merge.**

**Review threads:** all 3 Cursor panel findings (sub-group mirroring on the canonical mount, `get_type_hints` resolution against the source callback's globals, and the stderr docstring wording) were fixed in c5db184 and their threads are resolved. CodeRabbit's latest run reports no actionable comments. No merge conflict — the branch is `MERGEABLE` against `main`.

**Verified locally** (in an isolated worktree, at c5db184): full suite **2584 passed, 37 skipped**; `ruff format --check` + `ruff check` clean on all touched files. Also exercised the real CLI rather than trusting tests alone — `comfy model --help` lists all seven leaves (download/remove/list + list-folders/list-folder/search/show), `comfy models` is absent from root `--help` yet still resolves with the `[DEPRECATED — use `comfy model`]` banner. Non-breaking as claimed.

**The red `Windows Specific Commands` check is a pre-existing repo-wide CI bug, unrelated to this diff**, and I have now root-caused it rather than just re-running it. It fails in `Install Dependencies`, before any test executes:

```
error: failed to remove file `...\venv\Lib\site-packages\pydantic_core\_pydantic_core.cp312-win_amd64.pyd`: Access is denied. (os error 5)
  -> CalledProcessError (the uv pip install behind --fast-deps)
  -> ImportError: cannot import name '__version__' from 'pydantic_core' (unknown location)
```

`test-windows.yml:29-35` creates `venv`, activates it, `pip install -e .`, then runs `comfy … install --fast-deps`. That `comfy` process runs *from* `venv`, and `--fast-deps` has uv reinstall pydantic_core **into that same venv** — Windows cannot unlink a `.pyd` a live process has loaded, so the replace aborts and leaves the package gutted. It is intermittent because it only fires when the resolver picks a different pydantic_core build. Consistent with the evidence: the workflow is currently failing on ~every open branch (be-3001, be-2975, be-2982, be-3311, be-3297, be-3300, be-3285, be-3276 …) with one sporadic success, and this PR changes no dependency, packaging metadata, or workflow file — it only trips the `paths: comfy_cli/**` trigger.

The fix (give the ComfyUI workspace its own env so `comfy install` never mutates the interpreter's own venv) is a CI-config change that cannot be validated from macOS, so I have **deferred it to a follow-up ticket** rather than bolt it onto this PR. Left unlabeled for human triage since choosing among the fix options is a design call.

**Comment by mattmillerai** [comment]
🤖 The reviews loop filed Linear follow-up ticket(s) for review thread(s) deferred as out of scope for this PR:
- <https://linear.app/comfyorg/issue/BE-3323|BE-3323> — Fix repo-wide 'Windows Specific Commands' CI failure: uv cannot replace pydantic_core in the in-use venv

**Comment by mattmillerai** [comment]
Status check: all three cursor-review threads (canonical `model` mount sub-group asymmetry, `functools.wraps` hint resolution against the wrong globals, and the stderr docstring wording) were addressed in c5db184 and are resolved.

Local suite on the PR head is green: **2584 passed, 37 skipped**; `ruff format --check` and `ruff check` clean on all touched files.

The one red check — **Windows Specific Commands / test** — is not caused by this PR. It fails in the "Install Dependencies" step, where `uv pip install` of ComfyUI's cu126 `requirements.compiled` exits 2 and leaves a broken `pydantic_core` (`ImportError: cannot import name '__version__' from 'pydantic_core' (unknown location)`). That workflow is currently failing on essentially every branch in the repo (14 of the last 15 runs across unrelated PRs), so it's a repo-wide infra breakage rather than a regression here.

**Comment by bigcat88** [comment]
This PR currently **conflicts with `main`** — GitHub reports `mergeable: CONFLICTING`, so it needs a rebase before I can review it and I'm skipping it in the current review sweep.

Please rebase (or merge `main` in) and I'll pick it up on the next pass. `main` moved a fair bit in the last day, including #614 (ANSI sanitisation across the pretty-print call sites) and #628 (the duplicate `server_died` error-code fix that had `main` red), so a refresh may also clear unrelated CI noise on this branch.

**Review by skishore23 — CHANGES_REQUESTED** [review]
The design here is excellent and I verified the behavior end-to-end — but **this will land red on `main`**. Two of the PR's own tests pass at the head as-authored and fail once current `origin/main` is merged. It's a semantic conflict git can't see, so CI's green tick is stale. One small fix.

## The blocker: `_patch_urlopen` no longer intercepts

```
PR head as-authored:              2 passed
PR head + merge origin/main:      2 failed
```

Both failures are `TestEndToEnd`, and both are a real DNS attempt escaping the mock:

```
cloud_http_error … https://cloud.example.com/api/experiment/models:
<urlopen error [Errno 8] nodename nor servname provided, or not known>
```

**Root cause.** At the time this branch was written, `search.py:_http_get_json` called `urllib.request.urlopen(req, timeout=timeout)` directly, so `monkeypatch.setattr("urllib.request.urlopen", _fake)` intercepted it. On current `main`, `_http_get_json` was refactored to delegate:

```python
from comfy_cli.http import request_json
_, body = request_json(url, target, timeout=timeout, max_bytes=_MAX_RESPONSE_BYTES)
```

`request_json` opens through the module-level `_AUTHED_OPENER` (built with `NoRedirectHandler`), so `urllib.request.urlopen` is never called and the patch is a no-op. `search.py` auto-merges cleanly, which is exactly why nothing flagged it.

**Fix** — `main` already established the convention for this, in `tests/comfy_cli/command/models/test_search.py:225-229`. Swap the body of `_patch_urlopen` to:

```python
import comfy_cli.http as http_mod
monkeypatch.setattr(http_mod._AUTHED_OPENER, "open", _fake)
```

`_fake` still receives a `Request` object, so the rest of the helper is unchanged. Worth renaming it off `_patch_urlopen` while you're there.

## Everything else verified and working

I ran the merged branch against the real API to check the contract claims rather than trusting the tests:

**JSON contract holds exactly as described.** `comfy --json models list-folders`:
- **stdout** — one valid JSON envelope, `"ok": true`, `"command": "models list-folders"`, 135 folders
- **stderr** — `'comfy models …' is deprecated; use 'comfy model …'`
- exit 0

And `comfy --json model list-folders` → **0 bytes on stderr**, same envelope. So the canonical path is genuinely warning-free and the one-envelope-on-stdout contract is intact. Routing the warning through the `output` shim rather than bare `rprint` is the right call.

**Command tree is correct, with no collisions.** Introspected the live tree:
```
comfy model  : _download-worker, download, download-cancel, download-status,
               downloads, list, list-folder, list-folders, remove, search, show
comfy models : list-folder, list-folders, search, show   (hidden=True)
models help  : "[DEPRECATED — use `comfy model`] Discover models — …"
```
`Counter` over `models_command.app.registered_commands` shows **zero duplicate names**, so the `extend()` of `search.app`'s registrations doesn't shadow any local op.

**The group-callback caveat is moot today, and correctly anticipated.** `search.app.registered_callback is None` and `registered_groups == 0`, so nothing is lost by not carrying a callback onto `model`. Your comment already says "both are empty of sub-groups today" — good that the helper composes a source callback via `functools.wraps` for when that stops being true.

**The `get_type_hints` workaround is a genuinely sharp catch.** `functools.wraps` copying stringized annotations (from `from __future__ import annotations`) while `__globals__` still points at `deprecation.py` would `NameError` at CLI startup under Typer's hint resolution. Pre-resolving with `include_extras=True` to preserve `Option`/`Argument` metadata is right, and the bare-`except` fallthrough is well-justified in the comment.

**203 other tests pass** (`command/models`, `output/test_discovery.py`, `test_command_mentions.py`).

Fix the two-line mock target and I'll approve immediately — nothing else here needs to change.

**Comment by skishore23** [comment]
Reviewed at high effort — the direction is right, but the deprecation as shipped teaches users the old spelling and can't measure its own success. Findings verified by running the built CLI from the PR branch (ruff + the PR's tests themselves pass).

**UX inversion on the canonical noun.** The deleted mount carried search.py's `no_args_is_help=True`, but the merged `model` app is a bare `typer.Typer()` — verified: `comfy model` → exit 2, "Missing command", while the hidden deprecated `comfy models` → exit 0 with the full command table. The deprecated spelling is strictly friendlier than the one we're migrating everyone to.

**Envelopes still self-report the deprecated spelling.** The four discovery leaves hardcode `command="models …"` (search.py:261, 356, 644, 746) — verified: `comfy --json model list-folders` returns `"command": "models list-folders"`. Agents that derive follow-up invocations from `envelope.command` (the documented self-orientation loop) get funneled into the deprecated alias, and telemetry/replay pipelines round-trip a spelling that will eventually 404.

**The deprecated spelling is still taught by shipped surfaces the PR missed while updating SKILL.md:** error_codes.py:270/275/279/280 (remediation hints in every error envelope and `comfy discover`), cmdline.py:971 (the default-workflow missing-checkpoint nudge — the most common first-run path), README.md:373, search.py's module docstring, and in-command hints at search.py:300/671/716. The repo's own mention lint can't catch these because the hidden alias still resolves in the tree.

**Telemetry can't retire the alias.** Discovery leaves keep `@tracking.track_command("models")` (search.py:198/270/560/651) while local ops use `"model"`; since both spellings share the same CommandInfo objects, canonical and deprecated invocations emit identical events. There's no data to ever answer "has `comfy models` usage decayed enough to delete?" — the stated purpose of a hidden alias. Cheap fix: emit the signal from `warn_deprecated`, which runs exactly once per alias invocation.

**Import-time mutation hazards.** `models_command.app.registered_commands.extend(...)` (cmdline.py:1888) mutates another module's global, non-idempotently — verified: `importlib.reload(comfy_cli.cmdline)` takes `models.app` from 11 to 15 commands with duplicate leaves. It also means `models.app`'s command set depends on whether cmdline was imported first (tests/comfy_cli/test_tracking.py:477 and test_model_download_background.py drive `models.app` directly, so their surface is decided by pytest collection order). Building the merged noun in a local Typer instead of mutating the imported app avoids both.

**Callback asymmetry (latent).** `add_deprecated_alias` composes `source_app.registered_callback` but the canonical mount deliberately drops it — nothing enforces the invariant, so the day search.py grows an `@app.callback()` (e.g. a group-level `--where`), the hidden deprecated path honors it while the advertised `comfy model` path fails with "No such option".

Smaller: `comfy --json discover` now carries two full copies of the discovery subtree (+4KB / ~1k tokens per agent session-start with no `deprecated` marker on the alias leaves — `_command_to_dict` doesn't propagate the parent's hidden flag, so `models search` et al. report `hidden: false`); `deprecation.py`'s `warn_deprecated` open-codes `rprint` instead of `Renderer.warn()`, bypassing `sanitize_markup` at the boundary; test_model_alias.py duplicates `reset_singleton`/`_fake_resp`/`_patch_urlopen` from sibling test files (a models/ conftest.py would hold them); and the module docstring claims sibling consolidations "reuse" the helper in present tense — none exist yet.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by mattmillerai** [comment]
Fixed exactly as diagnosed in the review above — thank you for root-causing this so precisely.

`_patch_urlopen` in `tests/comfy_cli/command/models/test_model_alias.py` now patches `comfy_cli.http._AUTHED_OPENER.open` (matching `test_search.py`'s established convention) instead of the no-longer-reached `urllib.request.urlopen`. Also gave the fake response object a `.status` attribute, since `request_json` reads it. (Kept the `_patch_urlopen` name — `test_search.py`'s own equivalent helper kept it too despite the same opener switch, so renaming here would've been the odd one out.)

Separately, `origin/main` had also landed a lazy-subcommand rewrite of `cmdline.py` (`_RootGroup.lazy_subcommands`) since this branch's last sync, which textually conflicted with this PR's eager `app.add_typer`-based model/models merge. Rebased onto current `main` and re-wired the merge into the new architecture:
- `comfy_cli/command/models/models.py` now borrows `search.app`'s command/group registrations itself (was previously done in `cmdline.py`), so the `model` lazy-subcommand entry stays a plain module+attr lookup.
- `comfy_cli/command/models/search.py` builds `deprecated_alias_app` (via `add_deprecated_alias`) at module load, so the `models` (plural) lazy-subcommand entry can point at it directly.

Also stripped six `BE-2999` ticket references from comments/docstrings (three added by this rebase, three pre-existing) that the new `public-repo-hygiene` CI check — added on `main` while this branch was out of sync — correctly flagged now that this repo is public.

Verified: full pytest suite green except one pre-existing failure in `test_build.py` unrelated to this PR (reproduces identically on bare `origin/main` — a local not-signed-in credential state on this machine, not a regression). `ruff check`/`ruff format --check` clean on every file this PR touches.

**Review by skishore23 — APPROVED** [review]
Approving — the previous blocker is resolved. `_patch_urlopen` now patches `comfy_cli.http._AUTHED_OPENER.open`, both `TestEndToEnd` cases pass against the real `search.py`, and the full `tests/comfy_cli` suite on the **merged** tree (current main + this head) is 6045 passed / 1 failed, where the one failure (`test_node_deps.py::test_non_pep440_installed_version_is_unknown_not_a_crash`) fails identically on a plain `origin/main` export. Verified the contract by CLI: `--json model list-folders` → one envelope on stdout, empty stderr; `--json models list-folders` → same envelope + exactly one deprecation line on stderr. The alias does not force-import at startup (`sys.modules` after `comfy --version`/`env` is unchanged).

One thing I'd fold in before merge, since it directly undercuts the PR's own goal: **the error hints still steer agents to the deprecated spelling.** `error_codes.py:347,352,356` (`folder_not_found`, `model_not_found`, `models_show_local_unsupported`) and the live hints in `search.py:306,752,799` all say `comfy models …`, as does `search.py:1-8` and `comfy-build/SKILL.md:204`. An agent that follows `model_not_found`'s hint runs `comfy models search` and is immediately told to use `comfy model`. `test_command_mentions` can't catch it because the hidden alias still resolves. Seven strings.

Informational: main has since landed its own alias helper (`cmdline.py:_deprecated_alias_callback`, used for `distribution`→`build`) that always writes to stderr and re-stamps `renderer.command`; this PR's `deprecation.py` prints via `rprint` (stdout in TTY pretty mode) and doesn't re-stamp, so the canonical spelling's *error* envelope says `"command": "model"` while its *success* envelope says `"models list-folders"`. Same shape as the existing `skill`/`skills` precedent and unchanged for current consumers, so not a break — but the next consolidation should pick one helper.

**Comment by mattmillerai** [comment]
**agent-fleet merger — held (G12).** An approval on this PR reads as an unresolved ask: «One thing I'd fold in before merge, since it directly undercuts the PR's own goal: **the error hints still steer agents to the deprecated sp»

If that is not blocking, the fastest clear is a re-approval. Clears when: EVERY reviewer whose approval body carries an ask re-approves with a body that has none — a reviewer clears only their OWN body, so a different reviewer approving on top clears nothing; or a human with triage rights adds `merge-ok` (valid for the current head only); or add `do-not-merge` to keep holding. Editing the PR body or pushing does NOT clear it.

Replying here does not clear the hold on its own — the merger reads approvals and labels, not comment text. This notice is posted once per head; it will not repeat.
